highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Adrian von Arx
name: avarx
website: avarx.io
website_full: https://avarx.io
github: avarx
twitter: avarx_
tel: +41 31307 7883
tel_full: tel:+41313077883
google_maps: 'https://frappant.ch/location'
address: Birkenweg 61
postcode: 3013
city: Bern
country: Switzerland
google_analytics:

# needed for travis-ci build
exclude: [vendor]
